apiVersion: v1
kind: DeploymentConfig
metadata:
  name: busybox
spec:
  replicas: 1 #Super importante esto, meterlo sino no crea pods!
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: [ "/bin/sh", "-c", 'while true ; do echo "$MENSAJE1"; sleep 1; done;' ]
        env:
        - name: MENSAJE1
          value: "hola PHP"
  triggers:
  - type: ConfigChange
