apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: busybox 
        name: busybox
        command: [ "/bin/sh", "-c", 'while true ; do echo "$MYSQL_ROOT_PASSWORD"; sleep 1; done;' ]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-root-password
                key: MYSQL_ROOT_PASSWORD 
        ports:
        - containerPort: 3306
          protocol: TCP
