apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: demis-cm
    namespace: demis
  spec:
    containers:
    - image: mguazzardo/miphp:latest
      imagePullPolicy: Always
      name: miphp
      env:
        - name: MENSAJE1 
          valueFrom:
            configMapKeyRef:
              name: var1
              key: Saludo
  
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
