apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2021-07-26T18:20:02Z"
    generateName: demis-6c5ffb66c9-
    labels:
      app: demis
      pod-template-hash: 6c5ffb66c9
    name: demis-6c5ffb66c9-lppsn
    namespace: demis
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: demis-6c5ffb66c9
      uid: 75229f1b-df76-4619-8214-f5d31e6830c8
    resourceVersion: "473503"
    selfLink: /api/v1/namespaces/demis/pods/demis-6c5ffb66c9-lppsn
    uid: 94eac77a-b0ca-4d03-9e26-413900856e79
  spec:
    containers:
    - image: mguazzardo/miphp:latest
      imagePullPolicy: Always
      name: miphp
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-6f66b
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-6f66b
      secret:
        defaultMode: 420
        secretName: default-token-6f66b
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-07-26T18:20:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-07-26T18:20:06Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-07-26T18:20:06Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-07-26T18:20:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://aa144913545794e27b4ed88ae708b027e35e5ad8d62169dce9a84adecd15cb9c
      image: miphp:latest
      imageID: docker-pullable://mguazzardo/miphp@sha256:66a9f91eaebf2e780f69f8920ecaa9ac9abb181358086c4f0e06d01d7842f05d
      lastState: {}
      name: miphp
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-07-26T18:20:06Z"
    hostIP: 10.0.2.17
    phase: Running
    podIP: 172.17.0.7
    podIPs:
    - ip: 172.17.0.7
    qosClass: BestEffort
    startTime: "2021-07-26T18:20:02Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
