apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: website
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: website
    strategy: {}
    template:
      metadata:
        labels:
          deployment: website
      spec:
        containers:
        - image: ' '
          name: website
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: website
      app.kubernetes.io/component: website
      app.kubernetes.io/instance: website
    name: website
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: website
  status:
    loadBalancer: {}
kind: List
metadata: {}
